### PR TITLE
feat: LoggerEmailSender send all Database.Error fields

### LINKED ISSUE #590: Give more information about error in Error Notification mails
### New Feature Summary

Today we display only the errormessage,
but it can be tricky as sometime the errormessage is not enough

exemple:
```
Error Messages:
Value too long for field
```

my proposition is to send all Database.Error fields in the mail

### PR DESCRIPTION
**Pull request by alanjaouen**
resolve #590

### CODE REVIEW

**Comment by Damecek** [comment]
This is great, just received a bunch of such messages and was clueless. This will be very handy. Good job.

**Comment by Damecek** [comment]
@jongpie happy new year, could you please check out this PR? It would really help to clarify what exactly is the root cause of errors.

**Comment by jongpie** [comment]
@alanjaouen thanks so much for working on this, and apologies for the late response (same to you @Damecek)! I haven't been able to work on open source projects for the last few months, but I am back & working on catching up on this repo, starting with this PR.

Your changes look great to me - I think the inclusion of the error fields in the email will help a lot with troubleshooting bugs. I've also added a few extra asserts in a test class to validate that the error fields are included in the emails. I'll merge & release these changes later today!

**Comment by jongpie** [comment]
@alanjaouen and @Damecek this has now officially [been released as `v4.12.1`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.1)! 🎉🥳💃 If you have any more feedback on how to improve the error emails, please let me know.

Thanks again @alanjaouen for your work on this!

**Pull request merged**
