### PR TITLE
Configurable Apex Debug Log syntax via Logger Settings

### LINKED ISSUE #190: Add the ability for console/stdout logs to automatically include class and method names along with the message
To assist with tracing and debugging, we very often have code that looks something like the following:

```java
public class SomeClass {
  private static final String CLASS_NAME = SomeClass.class.getName();

  private static final String LOG_FORMAT = '{0} -- {1} -- {2}';

  public someMethod() {
    final String METHOD_NAME = 'someMethod()';

    Logger.debug( new LogMessage( LOG_FORMAT, CLASS_NAME, METHOD_NAME, 'Im here!' );

    // ...
  }
}
```

The existing LogMessage makes this very easy to set up, but having hardcoded method names (and less so class names) represents a source of technical debt and verbosity that complicate and distract from the actual non-logging code.

Making the class name and method name available to the logger when it spits out to the debug logs would be great! Perhaps as standardized message parameters like `{className}` and '{methodName}`

### PR DESCRIPTION
**Pull request by jamessimone**
* Fixes #190 by adding configurable merge field syntax to LoggerSettings__c.SystemLogMessageFormat__c, enabling output like @arbokrad requested

### CODE REVIEW

**Review by jongpie — COMMENTED** [review]
This looks really great overall! I added a few comments related to some of the guard clauses - let me know what you think.

**Comment by jamessimone** [comment]
@jongpie no worries, those were all great suggestions - thanks for reviewing!

**Comment by jongpie** [comment]
@jamessimone thanks for making those changes, I think this is ready to merge! Since I still don't have the package version creation automated, I added a commit to this PR for the new package ID. Feel free to merge the PR if you'd like, and I'll promote the package version afterwards (or I can handle the merge if you'd prefer).

Thanks again for working on this!

**Comment by jamessimone** [comment]
Sounds good, merged!

**Pull request merged**
