### PR TITLE
Enhancement to manually run LogBatchPurger via a button click

### PR DESCRIPTION
**Pull request by mar-ben**
This is an enhancement for #304. Below are the changes.

- added new LWC component `batchPurge`. This component displays the log metrics, a button to run the `logBatchPurger` and purge job details. 
- added a new lightning component tab for the LWC component `batchPurge`.
- added a new link button, `Batch Purge` that links to the `Batch Purge` lightning tab on the Log__c object. 
- included the new link button as a listview button on the Log__c object.

### CODE REVIEW

**Review by jongpie — CHANGES_REQUESTED** [review]
Hi @mar-ben - this looks incredible, thanks so much for putting this together! I've reviewed the code & tested it in a scratch org, and I have a few changes before we merge this:

- Metadata naming conventions - I typically try to include the word 'Log' in metadata API names to avoid clashing with existing metadata in orgs, so I've added several comments of metadata to rename
- The solution doesn't quite work when deployed to a scratch org (I tested using the Logger Console app):
    - The URL for the web link (the button that shows on the `Log__c` tab) is missing a leading `/`, so the current URL doesn't work
    - The custom tab isn't accessible by default, which causes an error for any user that doesn't have access to the tab - can you update the permission set `LoggerAdmin` so that the new custom tab's visibility is set to 'Visible'?
- I see references to a custom permission called 'CanExecuteLogBatchPurger`, but the custom permission itself seems to be missing
- I don't see a Jest test file for the new LWC - would you be able to add one? I'm happy to handle that if you'd like, just let me know what you prefer.
- Prettier should be run for the repo to standardize formatting in the new files (`npm run prettier:fix` is the specific command to run within the repo). If you're not familiar with installing/using prettier, let me know & I can handle this step.

Just let me know if you want help with any of these changes, and thanks again for working on this! This will be a great feature to have, I really appreciate you offering to work on this.

**Comment by mar-ben** [comment]
@jongpie  I have fixed the code review comments.

**Comment by jongpie** [comment]
@mar-ben thank you so much!! I'll review your changes over the weekend, and if I don't find any other potential changes, I'll try to get this merged within the next few days.

Thanks again for all of your hard work on this! 🥳

**Comment by jongpie** [comment]
@mar-ben apologies for the delay, I had some personal stuff come up this past weekend and have not had a chance to complete the code review on this PR. My schedule this week is a little chaotic, but I am hoping to complete the code review by this weekend.

**Comment by mar-ben** [comment]
@jongpie  no problem. take your time.

**Comment by jongpie** [comment]
@mar-ben I'm going to go ahead and merge this PR, and then I'll publish it in a new release in the next few days - apparently there is a limitation with GitHub Actions where the pipeline doesn't fully work for forked repos, so I'll workaround this for now. My plan is to combine your changes with another set of changes I'm working on, and then I'll release both sets of changes as `v4.7.8`. I'll let you know once I've published the release - thanks again for your help on this!

**Pull request merged**
