### PR TITLE
Adds logging methods for Database.LeadConvertResult class

### PR DESCRIPTION
**Pull request by jamessimone**
Helps @justin-lyon to log `Database.LeadConvertResult` instances

### CODE REVIEW

**Comment by jongpie** [comment]
Thanks @jamessimone! I'll finish reviewing & testing this today 🥳 

@justin-lyon, as long as no issues come up with testing this, then you can expect to see this in the next release, `v4.10.0`, which should be released in the next few days (for both the unlocked package and the managed package). PR #465 is the open PR for finishing `v4.10.0`.

**Review by jongpie — APPROVED** [review]
@jamessimone this looks great! Some of the `npm` dependencies & pre-commit hooks in the repo haven't been working correctly, so I added 2 commits to this branch to fix a few small things (including fixing the `prettier` issue in the pipeline), and slightly tweaking the method name in `LoggerMockDataCreator` for consistency. 

I'm going to merge this into my feature branch for PR #465 and then I should be able to get the next version finally released! Thanks again for working on this! 🥳

**Comment by jamessimone** [comment]
Woohoo! Thanks!On Mar 31, 2023, at 12:00 AM, Jonathan Gillespie ***@***.***> wrote:﻿
Merged #471 into feature/spring-23-api-version-upgrade.

**Comment by jongpie** [comment]
@justin-lyon it's ready! This is now available in the new release from today, [`v4.10.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.10.0)

Thanks again @jamessimone for implementing this!

**Pull request merged**
