### PR TITLE
Feature/489 raise exception in flow action

### PR DESCRIPTION
**Pull request by JMercie**
This PR tries to solve issue #489.

## Changes

1. Add a new flow variable to give the user control over whether or not they want to throw an exception to rollback database operations until the Log apex action is called.
2. Include changes in "addEntries" method of FlowLogger to add logic for this new scenario.
3. Add a test in FlowLogger_Tests class to cover the logic implemented.
4. Add a new custom Exception to throw for this particular case.

I'm more than open to any changes or suggestions you might have on this.

### CODE REVIEW

**Review by jongpie — CHANGES_REQUESTED** [review]
@JMercie this is awesome, thanks so much for working on this! 🥳 You've done a great job mimicking the existing code's styling & conventions. I've added several comments to lines with suggested changes, but essentially, there are 3 changes:

1. Instead of calling the new property `rollbackOperations`, I think calling it `showThrowFaultMessageException` would be more accurate & consistent with the rest of the codebase's naming conventions
2. Creating a top-level class called `AutolaunchedFlowException` could cause issues in orgs - it's safer to use the standard class `System.FlowException`
3. There's a DML statement in your test method - I don't think it's needed

Hope that all makes sense, but please let me know if you have any follow-up questions! Thanks again for your help

**Review by jongpie — APPROVED** [review]
@JMercie I reviewed this again after you pushed your last changes, and it looks great! Thanks so much for working on this. 

Later this week, I'll manually create the next release (the GitHub pipeline doesn't currently work for forked repos) - this will be released as `v4.11.1`.

**Comment by JMercie** [comment]
> @JMercie I reviewed this again after you pushed your last changes, and it looks great! Thanks so much for working on this.
> 
> Later this week, I'll manually create the next release (the GitHub pipeline doesn't currently work for forked repos) - this will be released as `v4.11.1`.

This was my first contribution to an OSS repo; the experience was great!
Thanks for the help and guidance on this, and for making it easy to contribute! @jongpie

**Comment by jongpie** [comment]
@JMercie that's amazing to hear, congrats on your first OSS contribution! I think this new functionality will be really great for logging in Flow, I really appreciate your help 🥳 

I'm nearly finished with the next release, and I've just pushed a few additional changes to your branch:

1. Your branch was missing a few commits from the `main` branch, so I've merged `main` into your branch
2. I've incremented the version number and name in `sfdx-project.json` (as well as several other files that reference the version number `v4.11.1`)
3. I've added an additional test method in each of these test classes - the new test methods are nearly identical to the test you added to `FlowLogger_Tests`, but with Nebula Logger's current architecture for logging in Flow, the test method has to be duplicated (with a few small changes) to ensure each invocable action is properly passing the new property `shouldThrowFaultMessageException` to the class `FlowLogger`. I forgot about this detail when I last reviewed your code, so I went ahead and took care of adding in these tests. The new test methods I added are...
  - `FlowLogEntry_Tests.it_should_throw_exception_when_shouldThrowFaultMessageException_is_set_to_true`
  - `FlowRecordLogEntry_Tests.it_should_throw_exception_when_shouldThrowFaultMessageException_is_set_to_true`
  - `FlowCollectionLogEntry_Tests.it_should_throw_exception_when_shouldThrowFaultMessageException_is_set_to_true`

I'm working on finalizing the release notes now - I hope to have this released in the next day or two!

**Comment by jongpie** [comment]
@JMercie I've just finished publishing the new release! It's now available as [`v4.11.1`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.11.1)

**Comment by JMercie** [comment]
@jongpie Thank you very much! Looking forward to keep helping! 😄

**Pull request merged**
