### PR TITLE
Track OrgLimits data on Log__c

### LINKED ISSUE #630: Capture OrgLimits data on Log__c
Currently, the `LogEntry__c` object has multiple fields related to tracking _transactional_ limits, [using the class `System.Limits`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm). I think it'd be helpful to capture and store _organizational_ limits on `Log__c`, [using the class `System.OrgLimits`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimit.htm#apex_class_System_OrgLimit). 

This data would probably need to be stored in a long text-area field (as JSON) and displayed using a custom component - the values returned by `OrgLimits` can be drastically different between orgs, based on the orgs licenses & add-ons, so it's not feasible to have a predefined number of fields on `Log__c`. This means that things like standard reports & dashboards probably can't be used to view this data, but using a custom component would at least provide admins/devs with a way to see the information.

### PR DESCRIPTION
**Pull request by jongpie**
# Core Unlocked Package Changes

- Resolved #630 by adding new functionality to track organization limits data, returned by [the class `System.OrgLimits`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimits.htm)
  - This data is automatically stored as JSON in the new field `Log__c.OrganizationLimits__c`
  - You can disable storing this data, using the new `LoggerParameter__mdt` record `StoreOrganizationLimits`
  - This data is displayed within a new "Organization Limits" tab on the `Log__c` flexipage, using a new LWC `logOrganizationLimits` (shown below). The design of this LWC is intended to mimic the existing formula fields shown on `LogEntry__c` that are used to track transaction limits.

    image
    
      - For comparison, this image shows the existing formula fields on `LogEntry__c` that are used to track transaction limits.
        
        image

- Added another new `LoggerParameter__mdt` record, `StoreTransactionLimits`, to control if transaction limits are retrieved from [the class `System.Limits`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm) & stored on `LogEntry__c`
  - Previously, transaction limits were always populated, with no way to disable it - using the `System.Limits` class does seem to have some overhead (namely, it uses CPU time), so being able to disable this functionality can, hilariously, help to reduce transaction limits usage.
- `loggerPageSection` LWC changes: Fixed some padding in `loggerPageSection.html` so it's more consistent with 'real' field section headers

### CODE REVIEW

**Comment by jongpie** [comment]
@jamessimone following up on [your comment about `OrgLimits.getMap()` failing during synchronous tests](https://github.com/jongpie/NebulaLogger/issues/630#issuecomment-1934093442), I _think_ it's maybe fixed now, kind of?

- I did initially have [a relevant flaky test failure](https://github.com/jongpie/NebulaLogger/actions/runs/8242899665/job/22542671132?pr=646) - my new test method failed once due to the returned JSON output not matching the expected value. Due to the length of the JSON, the assert message was truncated, so I couldn't see exactly why it didn't match (but calling `OrgLimits.getMap()` didn't seem to throw an exception). The same test passed during the same build in 1 of the 2 scratch orgs used in the pipeline (the base scratch org), but failed in the other (experience cloud scratch org).
- I then re-ran the build, and was able to [successfully run the pipeline for all steps](https://github.com/jongpie/NebulaLogger/actions/runs/8242899665/job/22543844733?pr=646), including running of all tests synchronously and asynchronously, creating a managed package version, and an unlocked package version.
- [This known issue](https://issues.salesforce.com/issue/a028c00000gAyK8AAK/metadata-deployment-with-run-apex-tests-gets-insufficient-privileges-error-by-using-orglimitsgetmap-method-in-apex-class) sounds relevant to the problem you've had, and it's now marked as "solution delivered".

The 1 flaky test failure seems a little suspicious, but I haven't been able to reproduce it. Do you remember if you were seeing a specific error message before when you tried to use `OrgLimits.getMap()`?

**Comment by jamessimone** [comment]
@jongpie let me take a look, at the time I was able to repro the issue with a synchronous test run

**Comment by jamessimone** [comment]
It seems to work now, great call!

**Comment by jongpie** [comment]
@jamessimone awesome, thanks for checking!

**Pull request merged**
